pipeline {
    agent any
    environment
    {
        cont_name = "app-cont"
        image_name = "app-image"
        version = "v1"
    }
    stages {
       
        stage('Build artifact') {
            steps {
                sh 'mvn clean install'
            }
        }
         stage('test') {
            steps {
                sh 'mvn test'
            }
        }
         stage('docker build') {
            steps {
                sh """ docker rm app || true
                docker build -t ${image_name}:${version} .
                """
            }
         }
             stage(' docker run') {
            steps {
                sh """ docker rm ${cont_name} || true
                docker run -d -p 5000:8080 --name ${cont_name} ${image_name}:${version}
                """
            }
        }
        }
    
}
